#define VERMELHO     "\x1b[31m"
#define VERDE        "\x1b[32m"
#define AZUL         "\x1b[34m"
#define AMARELO      "\x1b[33m"
#define ROSA         "\x1b[35m"
#define CIANO        "\x1b[36m"
#define RESET        "\x1b[0m"